resources:
  repositories:
  - repository: templates
    type: git
    name: templates
    ref: main
jobs:
- job: Terraform
  displayName: 'Terraform'
  steps:
  - template: build-terraform.yml@templates