# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: CI
    variables:
      - group: HML
      - name: ENV
        value: HML
    displayName: Continuous Integration
    jobs:
    - job: build
      displayName: Build Terraform Artfacts
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)'
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/terraform.zip' 
      - task: PublishPipelineArtifact@1
        inputs:
          artifactName: file
          targetPath: '$(Build.ArtifactStagingDirectory)'
          publishLocation: 'pipeline'
        displayName: 'Publish Terraform artifact'
  - stage: HML
    variables:
      - group: HML
      - name: HML
        value: HML
    jobs:
    - deployment: Deploy
      displayName: 'Plan HML'
      pool:
        vmImage: 'ubuntu-latest'
      environment: 'HML'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: DownloadPipelineArtifact@2
              inputs:
                artifactName: 'file'
                targetPath: '$(Build.SourcesDirectory)/terraform'
              displayName: 'Downloads'
            - task: TerraformInstaller@1
              inputs:
                terraformVersion: 'latest'
            
            - script: |
                export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
                export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
                export AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION)
                export TF_VAR_AWS_IAM_USER_KEY=$(AWS_ACCESS_KEY_ID)
                export TF_VAR_AWS_IAM_USER_SECRET_KEY=$(AWS_SECRET_ACCESS_KEY)
                terraform init
                terraform workspace select -or-create $(ENV)
                terraform plan -var-file=./tfvars/$(ENV).tfvars
                terraform apply -var-file=./tfvars/$(ENV).tfvars -auto-approve
